name: Deploy Frontend To Production Server

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Build application
      run: npm run build
      env:
        CI: true
        VITE_API_BASE_URL: ${{ secrets.VITE_API_BASE_URL }}
        VITE_SECRET_KEY: ${{ secrets.VITE_SECRET_KEY }}

    - name: Remove the dist folder from VPS
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        password: ${{ secrets.VPS_PASSWORD }}
        script: |
          cd ${{ secrets.APP_PATH }}
          rm -r dist
    
    - name: Deploy To VPS
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        password: ${{ secrets.VPS_PASSWORD }}
        source: "dist/"
        target: ${{ secrets.APP_PATH }}
